parameters:
  - name: version
    displayName: Version
    type: string
    default: '4.2.0.1'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x86|x64|ARM'
  buildConfiguration: 'Release'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: "Install .NET Core SDK"
  inputs:
    version: 6.0.x
    performMultiLevelLookup: true
    includePreviewVersions: false # Required for preview versions

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '6.2.x'
    
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    platform: 'Neutral'
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxPackageDir="$(appxPackageDir)" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload'

